# fly.toml app configuration file generated for pokemonshop on 2023-08-17T01:00:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokemonshop"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  DATABASE_URL= "mongodb+srv://Puzzles65:Trung1998@cluster0.ebcrw7u.mongodb.net/pokemon-shop?retryWrites=true&w=majority"
  SECRET= "SEIRocks"